'use strict';
/* ================= 内置示例数据《长夜档案》 =================
   原创示例剧情（虚构）：幽庭镇 1893 年霍桑宅大火背后的“换命仪式”，
   五姓家族的百年秘密，在 2026 年长夜归时被两位主角揭开。
   人物 ≥100（含家族/镇民/守夜会/灵体/灵魂/动物），
   关系简单（亲子）与复杂（双面搭档/义兄宿敌/恋人背叛）并存，
   时间线跨越 1893 → 2026，含反转（巴兹=仪式执行者）、
   伏笔（灰猫七爷与“第七封信”）与多线串联（所有旧案指向同一场仪式）。 */
const SampleData = {
  name: '示例工程 · 长夜档案（幽庭镇）',
  persons: [
    /* ---------- 霍桑家族（1893 大火元凶宅邸） ---------- */
    { id: 'h1', name: '老埃尔玛·霍桑', group: '霍桑家族', position: '家主 · 占卜师', tag: ['占卜', '契约主笔'], intro: '幽庭镇最古老的当家人，一手操办“五姓契约”，1899 年冬夜中风而终，死前反复念叨“灰猫不要来”。' },
    { id: 'h2', name: '弗朗西斯·霍桑', group: '霍桑家族', position: '长子 · 镇长', tag: ['沉默', '镇长'], intro: '老埃尔玛长子，火灾善后的实际操办人，终其一生封存档案室，晚年失语。' },
    { id: 'h3', name: '伊莱扎·霍桑', group: '霍桑家族', position: '长女', tag: ['灰衣女士', '生者'], intro: '老埃尔玛长女，1893 年火灾唯一的目击证人；1910 年坠楼，死后化为“灰衣女士”灵体，百年守宅。' },
    { id: 'h4', name: '罗莎琳德·霍桑', group: '霍桑家族', position: '次女', tag: ['下嫁', '卡尔弗特家媳'], intro: '老埃尔玛次女，嫁入卡尔弗特家，生养三子，晚年写下家书“铁盒里锁着 1893 年的真相”。' },
    { id: 'h5', name: '奥古斯特·霍桑', group: '霍桑家族', position: '三子 · 灵学家', tag: ['降灵', '疯癫'], intro: '灵学研究会创始人，曾三次降灵试图与“火焰夫人”谈判，1920 年疯癫，用粉笔在卧室画满火圈。' },
    { id: 'h6', name: '修伯特·霍桑', group: '霍桑家族', position: '第三代', tag: ['继承人'], intro: '弗朗西斯之子，1939 年“空袭夜”后随档案消失，成为战后悬案。' },
    { id: 'h7', name: '玛格丽特·霍桑', group: '霍桑家族', position: '孙女', tag: ['井中新娘'], intro: '弗朗西斯之女，1910 年投井身亡（生前被订婚给“井”，村人以井中新娘称之），怨灵封井。' },
    { id: 'h8', name: '诺曼·霍桑', group: '霍桑家族', position: '养子 · 园丁之后', tag: ['养子', '战俘'], intro: '伊莱扎收养的园丁遗孤，1916 年入伍，战后归乡未果，改名换姓生活。' },
    { id: 'h9', name: '布洛克', group: '霍桑家族', position: '管家', tag: ['忠诚'], intro: '霍桑宅七十年老管家，知晓宅中每一条密道，1955 年守园过世。' },
    { id: 'h10', name: '老珀尔', group: '霍桑家族', position: '园丁', tag: ['怨灵'], intro: '1896 年被误认纵火者自缢于玫瑰棚，血手园丁之怨即其灵体。' },
    { id: 'h11', name: '埃达', group: '霍桑家族', position: '女仆长', tag: ['失踪'], intro: '1893 年火灾当晚失踪的年轻女仆长，后世在旧井壁发现她的梳子。' },
    { id: 'h12', name: '普露', group: '霍桑家族', position: '女仆', tag: ['见证'], intro: '唯一活过 1893 火灾的女仆，终生不夜宿镇中；遗物是半页烧焦的信。' },
    { id: 'h13', name: '乔治', group: '霍桑家族', position: '马车夫', tag: ['夜行'], intro: '火灾夜驾马车载埃尔玛“出门”，马车再未回镇，留下两条铁轨印。' },
    { id: 'h14', name: '温特医生', group: '霍桑家族', position: '镇医', tag: ['记录'], intro: '负责验尸的镇医，留下三百页《幽庭死因手记》，其中 1893 年那页被撕。' },
    /* ---------- 卡尔弗特家族（五姓之一） ---------- */
    { id: 'c1', name: '埃德加·卡尔弗特', group: '卡尔弗特家族', position: '法官', tag: ['五姓'], intro: '五姓契约的公证人，1900 年宣判“火宅为意外”并销毁物证，晚年在教堂台阶上脑溢血。' },
    { id: 'c2', name: '温妮莎·卡尔弗特', group: '卡尔弗特家族', position: '家主 · 医生', tag: ['接生'], intro: '罗莎琳德侄女，战后继承大宅，诊所兼产房；1950 年临终托付一沓匿名信。' },
    { id: 'c3', name: '克劳德·卡尔弗特', group: '卡尔弗特家族', position: '长子', tag: ['怯懦'], intro: '温妮莎长子，畏火，1960 年溺毙于自家泳池，死前名字被人用火漆封住。' },
    { id: 'c4', name: '兰斯洛特·卡尔弗特', group: '卡尔弗特家族', position: '次子 · 军官', tag: ['骑手'], intro: '温妮莎次子，1942 年坠山，雾中骑手灵体即其执念——要送一封信回宅。' },
    { id: 'c5', name: '埃莉诺·卡尔弗特', group: '卡尔弗特家族', position: '长女', tag: ['作家'], intro: '温妮莎长女，写《幽庭镇鬼话》传世，2010 年临终说“最后一行我写错了”。' },
    { id: 'c6', name: '汉克', group: '卡尔弗特家族', position: '园丁', tag: ['换命见证'], intro: '卡尔弗特家园丁，曾替两家人埋“生辰匣”，生前守密，死后其孙 2025 年交还原物。' },
    { id: 'c7', name: '罗德里克·卡尔弗特', group: '卡尔弗特家族', position: '上校', tag: ['倔强'], intro: '埃德加之弟，镇压 1893 年“进镇调查”的宪兵队，被家族书信断交。' },
    { id: 'c8', name: '露西塔', group: '卡尔弗特家族', position: '歌女', tag: ['风铃'], intro: '罗德里克座上宾，歌声里有鸟鸣，1932 年死于舞台失火，风铃女灵体之始。' },
    { id: 'c9', name: '奥尔加', group: '卡尔弗特家族', position: '管家', tag: ['锁钥'], intro: '卡尔弗特宅管家，保管地窖钥匙五十年，1958 年把钥匙熔进自己的金牙。' },
    { id: 'c10', name: '杰弗里·卡尔弗特', group: '卡尔弗特家族', position: '幼子', tag: ['败家'], intro: '埃莉诺之弟，1995 年把老宅卖给图勒，签完字当晚从二楼跳下。' },
    { id: 'c11', name: '塞西莉亚·卡尔弗特', group: '卡尔弗特家族', position: '堂妹', tag: ['档案'], intro: '埃莉诺堂妹，2012 年留下“第七封信”与一只灰猫照片，信至今未寄出。' },
    { id: 'c12', name: '本杰明·卡尔弗特', group: '卡尔弗特家族', position: '历史学家', tag: ['契约研究者'], intro: '第一位研究“五姓契约”的学者，1974 年说“契约不是五个姓氏，是四姓换一命”，从此失踪。' },
    /* ---------- 幽庭镇民 ---------- */
    { id: 't1', name: '沙利文', group: '幽庭镇民', position: '镇长', tag: ['遮丑'], intro: '1893 年镇长，以“鸦灾”结案，1898 年开会时突然说不出“火”字。' },
    { id: 't2', name: '韦伯', group: '幽庭镇民', position: '牧师', tag: ['驱魔', '妥协'], intro: '老教堂牧师，主持过三场“非婚礼”仪式，1912 年把圣水换成井水后病倒。' },
    { id: 't3', name: '贝丝', group: '幽庭镇民', position: '药剂师', tag: ['梦境'], intro: '镇药房伙计，长年失眠，梦见火场细节三十三次，写在“梦簿”上。' },
    { id: 't4', name: '伊莫金', group: '幽庭镇民', position: '女巫', tag: ['守井人'], intro: '井边小屋的女巫，代代守井，1900 年封井时在井口埋下一片金翅雀羽毛。' },
    { id: 't5', name: '索尔', group: '幽庭镇民', position: '钟表匠', tag: ['钟楼'], intro: '钟楼修钟人，修好过“停摆七分钟”的钟，后来钟每夜响 13 下。' },
    { id: 't6', name: '厄尔', group: '幽庭镇民', position: '面包师', tag: ['暗号'], intro: '面包房老板，用面包屑当情报，1920 年面包炉里烤出半封煤信。' },
    { id: 't7', name: '冈特', group: '幽庭镇民', position: '旅店老板', tag: ['夜宿'], intro: '老旅店主人，1925 年一个“钟点房”无人住却天天续费；账本最后一页写“客人已寄”。' },
    { id: 't8', name: '麦克布莱德', group: '幽庭镇民', position: '警长', tag: ['悬案'], intro: '警长，经手幽庭十八宗怪案，1932 年死前把档案拆成三份寄走。' },
    { id: 't9', name: '科迪', group: '幽庭镇民', position: '渔夫', tag: ['雾'], intro: '老渔夫，见过雾中骑手三次，每次送信给“霍桑小姐”；他钓上来的不是鱼。' },
    { id: 't10', name: '玛莎', group: '幽庭镇民', position: '寡妇', tag: ['谣言源'], intro: '镇上的谣言总泵，1935 年却忽然沉默，只留一句话“火里有人笑”。' },
    { id: 't11', name: '菲奥娜', group: '幽庭镇民', position: '助产士', tag: ['接生'], intro: '接生过四十六个孩子，其中三个“婴儿从未哭过”；1940 年在病历写“啼哭被换走了”。' },
    { id: 't12', name: '阿奇', group: '幽庭镇民', position: '杂货商', tag: ['货单'], intro: '货栈老板，账本上连续 40 年记着同一位“灰衣女士”每月买蜡烛。' },
    { id: 't13', name: '迪伦', group: '幽庭镇民', position: '邮差', tag: ['邮路'], intro: '邮差，负责投递“查无此人”的地址；1945 年遗物中有一封寄给“未来的收信人”。' },
    { id: 't14', name: '汉森', group: '幽庭镇民', position: '木工', tag: ['门'], intro: '木匠，1928 年亲手钉死霍桑宅十扇门，说“每扇门背后都该有一条路”。' },
    { id: 't15', name: '奥列格', group: '幽庭镇民', position: '铁匠', tag: ['铁衣'], intro: '铁匠，打三副铁护身符护住全家，十字路口锻铁时火星成鸦形。' },
    { id: 't16', name: '克拉克', group: '幽庭镇民', position: '教师', tag: ['课本'], intro: '小学教师，1935 年发现班上一半孩子的家谱里都没有“出生年份”。' },
    { id: 't17', name: '茜拉', group: '幽庭镇民', position: '学生', tag: ['摇篮鬼'], intro: '克拉克班上的学生，1910 年病死，之后的夜里教室摇篮自摇。' },
    { id: 't18', name: '巴尼', group: '幽庭镇民', position: '酒鬼', tag: ['真话'], intro: '酒馆常客，醉后真话：“1893 年那夜，我在火里看见两个我。” 1901 年溺亡。' },
    { id: 't19', name: '托比', group: '幽庭镇民', position: '孤儿', tag: ['迷宫鬼童'], intro: '孤儿院孩子，1915 年迷路于霍桑宅迷宫，灵体在墙内拍手引路。' },
    { id: 't20', name: '菲比', group: '幽庭镇民', position: '记者', tag: ['铅字'], intro: '镇报女记者，1893 年稿子被撤，晚年主编《旧镇笔录》，被问“为什么不用铅字印火”时挂断电话。' },
    { id: 't21', name: '亨德森', group: '幽庭镇民', position: '医生', tag: ['接生纪录'], intro: '温特后任镇医，1930 年整理温特手记时，发现自己签名下多了“另一只手”的签名。' },
    { id: 't22', name: '莫特', group: '幽庭镇民', position: '殡葬师', tag: ['名单'], intro: '殡葬师，登记“火葬”时总多一出戏，1948 年临终列出一张 40 年未寄的讣告。' },
    /* ---------- 守夜会 / 驱魔人 ---------- */
    { id: 'w1', name: '奥古斯都·佩尔', group: '守夜会', position: '会长', tag: ['守夜'], intro: '守夜会首任会长，1897 年带“白猫蜡烛”进宅驱火，1936 年死于自己维护的烛台旁。' },
    { id: 'w2', name: '海伦', group: '守夜会', position: '执事', tag: ['封印'], intro: '执事，负责给“不该埋的”东西重新上锁，1945 年封完最后一箱后自沉进井口。' },
    { id: 'w3', name: '拉文', group: '守夜会', position: '学徒', tag: ['失踪'], intro: '守夜会最年轻学徒，1918 年“降灵”后失踪，只留半页写满“她回来了”的纸。' },
    { id: 'w4', name: '西奥多', group: '守夜会', position: '学者', tag: ['注释'], intro: '释灵学家，注释过七本禁书，1923 年书页边写下“别让第七封寄出”。' },
    { id: 'w5', name: '金妮', group: '守夜会', position: '文书', tag: ['誊写'], intro: '守夜会文书，誊抄 30 年档案，1950 年失踪时誊本里夹着一片金翅雀羽毛。' },
    { id: 'w6', name: '菲尔伯特', group: '守夜会', position: '顾问', tag: ['教父'], intro: '老顾问，1940 年“空袭夜”被请出山，随身账本记录的“次数”超出夜数。' },
    { id: 'w7', name: '马库斯', group: '守夜会', position: '前任会长', tag: ['换命'], intro: '创会前的驱魔人，1900 年承认“用一命换了十载平安”，自缢于钟楼。' },
    { id: 'w8', name: '凯瑟琳', group: '守夜会', position: '法师', tag: ['火焰术'], intro: '唯一能控“明火”的法师，1949 年练习时烧掉自己的左袖，之后只穿黑衣。' },
    { id: 'w9', name: '伊恩', group: '守夜会', position: '圣兵', tag: ['护卫'], intro: '守夜会护卫，持银钉守在宅门四十年，1926 年拒绝“换班”后一夜白头。' },
    { id: 'w10', name: '艾琳', group: '守夜会', position: '缝尸人', tag: ['针线'], intro: '缝尸人，为“不该缝合”的遗体收线；1935 年最后一针留在自己手心。' },
    { id: 'w11', name: '查尔斯·佩尔', group: '守夜会', position: '战后会长', tag: ['重建会', '守密人'], intro: '奥古斯都之子，战后重建守夜会，1980 年把“契约”锁进保险柜后对外公布“仪式已解”。' },
    /* ---------- 灵体 / 鬼魂 ---------- */
    { id: 'g1', name: '灰衣女士', group: '灵体·宅邸', position: '灵体', tag: ['守宅灵', '引路人'], intro: '伊莱扎·霍桑的亡魂，百年游弋于宅邸回廊，只向“愿意听真相的人”招手。' },
    { id: 'g2', name: '火焰夫人', group: '灵体·火', position: '恶灵', tag: ['烈火之灵', '换命仪式'], intro: '1893 年大火中凝聚的恶灵，以“换命”为食；终局揭示其本体是当年被献祭的“第一命”。' },
    { id: 'g3', name: '摇篮鬼', group: '灵体·故居', position: '灵体', tag: ['摇篮'], intro: '茜拉的灵体，在旧教室的摇篮旁哼歌，听到“火光”就停。' },
    { id: 'g4', name: '吊钟鬼', group: '灵体·钟楼', position: '灵体', tag: ['十三响'], intro: '从前钟楼敲钟人的灵体，每夜敲 13 下——第 13 下只有“该听见的人”能听见。' },
    { id: 'g5', name: '迷宫鬼童', group: '灵体·花园', position: '灵体', tag: ['引导'], intro: '托比的灵体，在树篱迷宫里拍手引路，给迷路的人指“出口也是入口”。' },
    { id: 'g6', name: '井中新娘', group: '灵体·井', position: '灵体', tag: ['怨'], intro: '玛格丽特的灵体，封于老井，月圆夜井水泛白，她的婚书背面写“我不愿”。' },
    { id: 'g7', name: '石像鬼守护', group: '灵体·宅邸', position: '石灵', tag: ['守门'], intro: '宅邸门楣石兽的附灵，对“持灰猫信物者”让路，其余来客不许进门。' },
    { id: 'g8', name: '血手园丁', group: '灵体·花园', position: '怨灵', tag: ['玫瑰花'], intro: '老珀尔的怨灵，在玫瑰棚徘徊，谁动他的花，谁的手就会沾上他的血。' },
    { id: 'g9', name: '铁链老奶奶', group: '灵体·疗养院', position: '灵体', tag: ['锁链魂'], intro: '废弃疗养院的幽灵，走廊尽头拖铁链，据说 1955 年她“锁住了不该放的东西”。' },
    { id: 'g10', name: '雾中骑手', group: '灵体·山路', position: '灵体', tag: ['送信'], intro: '罗德里克上校（一说兰斯洛特）的亡魂，山雾里纵马，只为把一封信送回老宅。' },
    { id: 'g11', name: '镜中双人', group: '灵体·更衣室', position: '灵体', tag: ['镜中影'], intro: '更衣室长镜里的双人灵体，一个笑一个哭，1963 年事件后镜面再未复原。' },
    { id: 'g12', name: '风铃女', group: '灵体·戏台', position: '灵体', tag: ['歌声'], intro: '露西塔的亡魂，旧戏台风铃在她“生前”的唱段里响，只唱给听得懂的人。' },
    { id: 'g13', name: '地下室小女孩', group: '灵体·孤儿院', position: '灵体', tag: ['旧院魂'], intro: '1977 年孤儿院火灾中消失的孩子，在地下室画火柴人，画像烧不坏。' },
    { id: 'g14', name: '黑猫之灵', group: '灵体·猫', position: '灵体', tag: ['分身'], intro: '灰猫七爷的一缕分灵，夜里巡宅，见它者次日会收到“第七封信”的预告。' },
    { id: 'g15', name: '守灯人', group: '灵体·灯塔', position: '灵体', tag: ['海上'], intro: '废弃灯塔的守灯人灵体，为“夜行者”点灯——上一个点灯的是他自己的鬼魂。' },
    { id: 'g16', name: '许愿鬼', group: '灵体·老井', position: '灵体', tag: ['代价'], intro: '老井许愿灵，收愿望还“等价的灯火”；向它许愿的人，十年后都会烧掉一封信。' },
    /* ---------- 灵魂 / 降灵 ---------- */
    { id: 's1', name: '赛姬', group: '灵魂·降灵', position: '预言师', tag: ['金色笔'], intro: '流浪预言师，用金色笔写“未发生的讣告”，1893 年前夜写了 13 份，只有 1 份寄出。' },
    { id: 's2', name: '奥菲莉亚', group: '灵魂·降灵', position: '通灵人', tag: ['吊桥'], intro: '通灵人，走吊桥替人传话；1910 年传话“灰衣女士说自己怕冷”后吊桥封锁。' },
    { id: 's3', name: '忘川船夫', group: '灵魂·摆渡', position: '摆渡灵', tag: ['雾河'], intro: '雾河的摆渡灵，渡活人也渡死人，撑的是同一只白船，收的是“一句真话”。' },
    { id: 's4', name: '梦魇织者', group: '灵魂·梦', position: '织梦', tag: ['噩梦'], intro: '织梦者，把整座镇的噩梦缝成毯；1955 年后毯上有两个人名怎么拆都拆不掉。' },
    { id: 's5', name: '摆灯人', group: '灵魂·巡夜', position: '巡夜', tag: ['七星灯'], intro: '巡夜摆灯人，沿旧路摆七盏灯，哪盏灭了哪段记忆就熄。' },
    { id: 's6', name: '巡魂人', group: '灵魂·巡夜', position: '巡夜', tag: ['名录'], intro: '巡魂人，拿一本无形名录核对“镇上的活人”，1930 年发现名录多了 1 人。' },
    { id: 's7', name: '收灵人', group: '灵魂·巡夜', position: '收灵', tag: ['收函'], intro: '收灵人，替灵体收信；1945 年拒收一封署名“未来收信人”的信，被风吹进邮差包。' },
    { id: 's8', name: '渡鸦祭司', group: '灵魂·渡鸦', position: '祭司', tag: ['鸦群'], intro: '渡鸦祭司，统率鸦群监视“火”，1893 年鸦群曾在宅顶排成人形。' },
    /* ---------- 动物 / 超自然生物 ---------- */
    { id: 'a1', name: '灰猫七爷', group: '动物·守护', position: '老猫', tag: ['老猫', '守密者'], intro: '活了百余年的大灰猫，每代守护“契约”的秘密；只有它看得出谁带着“火气”。' },
    { id: 'a2', name: '黑猫墨玉', group: '动物·守护', position: '猫', tag: ['守夜猫'], intro: '伊芙琳的猫，2023 年入住当夜就堵在阁楼梯上，后来每逢满月坐井边。' },
    { id: 'a3', name: '乌鸦使者', group: '动物·报信', position: '鸦', tag: ['渡鸦祭司弟子'], intro: '渡鸦祭司的传讯鸦，专送“黑字”，1893 年它在窗台上叼走半页契约。' },
    { id: 'a4', name: '三眼猎犬', group: '动物·守夜', position: '犬', tag: ['守夜会'], intro: '守夜会养的三眼猎犬，能看见“看不见”的客人，1936 年会对空吠三声。' },
    { id: 'a5', name: '玄狼阿赫', group: '动物·林间', position: '狼灵', tag: ['七爷旧识'], intro: '森林狼灵，百年前与七爷并肩见证第一桩仪式；春天月圆时会回镇台阶上坐一夜。' },
    { id: 'a6', name: '白马幽灵', group: '动物·雾', position: '马', tag: ['骑手坐骑'], intro: '雾中骑手的白马，蹄声空洞，进雾前会回望老宅三楼亮灯的窗。' },
    { id: 'a7', name: '金翅雀信使', group: '动物·信使', position: '雀', tag: ['第七封信'], intro: '金翅雀信使，百年只传一封“第七封信”——它出现，意味着有人该寄信了。' },
    { id: 'a8', name: '娜迦尼', group: '动物·井', position: '蛇灵', tag: ['井中'], intro: '老井守护蛇灵，人面蛇身，只问来者一句“你把什么换走了”。' },
    { id: 'a9', name: '猫头鹰守夜人', group: '动物·守夜', position: '鸮', tag: ['巡夜'], intro: '夜巡猫头鹰，在镇上三座尖顶间轮流站岗，谁家灯后多出人影它就盯谁家。' },
    { id: 'a10', name: '老鼠先知', group: '动物·洞', position: '鼠', tag: ['地听'], intro: '地底老鼠先知，以“地听”报信；1928 年它带领全镇老鼠搬离钟楼。' },
    { id: 'a11', name: '蝶妖', group: '动物·幻境', position: '蝶', tag: ['引路'], intro: '幻境引路蝶，伴雾起舞，能把人带进“1893 年的那一天”，代价是带回一片记忆。' },
    { id: 'a12', name: '灰猫幼崽月', group: '动物·守护', position: '幼猫', tag: ['传人'], intro: '七爷的传人，2025 年冬天出生，尾巴尖有一撮白色，被伊芙琳抱回家。' },
    /* ---------- 当代线（2023-2026） ---------- */
    { id: 'n1', name: '伊芙琳·格里姆', group: '当代·长夜归', position: '租客', tag: ['租客', '记忆者'], intro: '主角一：入住霍桑宅的年轻租客，总能“记起”1893 年的细节——她其实是那场仪式的未偿之债。' },
    { id: 'n2', name: '雨果·克劳斯', group: '当代·长夜归', position: '侦探', tag: ['侦探', '狼友'], intro: '主角二：调查图勒坠梯案的侦探，数月前在山里救过一头“不像狼的狼”。' },
    { id: 'n3', name: '凯拉', group: '当代·长夜归', position: '主播', tag: ['视频'], intro: '镇电视台新闻主播，2025 年最后一次报道“老宅有货轮烟囱的烟”，之后再无人见她。' },
    { id: 'n4', name: '马库斯·韦尔', group: '当代·长夜归', position: '记者', tag: ['老报人'], intro: '菲比的接班人，镇报老记者，手里有 1893 年撤稿的铅字版。' },
    { id: 'n5', name: '林恩', group: '当代·长夜归', position: '法医', tag: ['鉴定'], intro: '法医，鉴定图勒“坠梯”时看到梯级上不该存在的第三层抓痕。' },
    { id: 'n6', name: '小蔡', group: '当代·长夜归', position: '助理', tag: ['猫粮'], intro: '伊芙琳的助理，唯一能让黑猫墨玉坐进纸箱的人。' },
    { id: 'n7', name: '图勒', group: '当代·长夜归', position: '房东', tag: ['老宅主'], intro: '2001 年买下霍桑宅的房东，2024 年从阁楼梯摔下，死前说“第七封……是猫送来的”。' },
    { id: 'n8', name: '迪克', group: '当代·长夜归', position: '承包商', tag: ['翻修'], intro: '负责翻修宅子的承包商，第一晚就罢工：“墙体后面有心跳声。”' },
    { id: 'n9', name: '薇拉', group: '当代·长夜归', position: '网红', tag: ['探灵'], intro: '探灵主播，2025 年直播“夜探霍桑宅”，镜头里只有她一个人，弹幕却说看见两个。' },
    { id: 'n10', name: '巴兹', group: '当代·长夜归', position: '灵异博主', tag: ['解密者', '掌炉人'], intro: '《幽庭档案》博主，热度最高的“解密者”；真实身份是查尔斯·佩尔之孙，最终被火焰夫人附体——他就是仪式的执行者。' },
    { id: 'n11', name: '阿曼达', group: '当代·长夜归', position: '心理师', tag: ['催眠'], intro: '心理师，给伊芙琳做“记忆回溯”催眠，第四次催眠后拒绝再谈：“那部分不归心理学管。”' },
    { id: 'n12', name: '佩姬', group: '当代·长夜归', position: '镇长', tag: ['后人'], intro: '沙利文镇长曾孙女，2026 年上任第一天就收到“退回的火情记录”。' },
    { id: 'n13', name: '朱莉', group: '当代·长夜归', position: '猫咖主', tag: ['七爷寄养'], intro: '猫咖老板，收留过一只“脖子上有白毛的灰猫”，她说那是七爷的“休假”。' },
    { id: 'n14', name: '所罗门', group: '当代·长夜归', position: '考古学家', tag: ['契约石'], intro: '考古学家，2025 年挖出刻着四个姓氏和一道手印的“契约石”。' },
    { id: 'n15', name: '贝蒂', group: '当代·长夜归', position: '图书馆员', tag: ['旧报'], intro: '镇图书馆员，管理 1893 年“火灾专档”，只允许“被灰猫带来的人”翻阅。' },
    { id: 'n16', name: '詹米', group: '当代·长夜归', position: '高中生', tag: ['狗'], intro: '高中生，傍晚牵三眼猎犬散步，犬在霍桑宅门口坐成一尊石像。' },
    { id: 'n17', name: '诺拉', group: '当代·长夜归', position: '巡警', tag: ['夜班'], intro: '夜班巡警，午夜巡逻时总在时钟 13 响的瞬间到岗——虽然钟最多只敲 12 下。' },
    { id: 'n18', name: '奥托', group: '当代·长夜归', position: '咖啡店主', tag: ['常客'], intro: '老宅对面咖啡店老板，给侦探留窗边的位置，说“那桌能看到阁楼的灯”。' }
  ],

  relations: [
    /* ---- 霍桑家族：家族链 ---- */
    { sourceId: 'h1', targetId: 'h2', relationType: '父子', desc: '长子，继承家业与“契约”', strength: 9, time: '1880' },
    { sourceId: 'h1', targetId: 'h3', relationType: '父女', desc: '长女，契约的目击人', strength: 9, time: '1875' },
    { sourceId: 'h1', targetId: 'h4', relationType: '父女', desc: '次女，下嫁卡尔弗特家', strength: 8, time: '1888' },
    { sourceId: 'h1', targetId: 'h5', relationType: '父子', desc: '三子，灵学家', strength: 8, time: '1884' },
    { sourceId: 'h2', targetId: 'h6', relationType: '父子', desc: '第三代', strength: 9, time: '1918' },
    { sourceId: 'h2', targetId: 'h7', relationType: '父女', desc: '井中新娘', strength: 9, time: '1910' },
    { sourceId: 'h6', targetId: 'h7', relationType: '兄妹', desc: '同父姐弟', strength: 8, time: '1910' },
    { sourceId: 'h3', targetId: 'h8', relationType: '养子', desc: '养子，园丁遗孤', strength: 7, time: '1913' },
    { sourceId: 'h8', targetId: 'h7', relationType: '养兄妹', desc: '一起长大', strength: 6, time: '1915' },
    { sourceId: 'h4', targetId: 'c2', relationType: '亲戚', desc: '侄女，后为家主', strength: 6, time: '1919' },
    { sourceId: 'h2', targetId: 'h10', relationType: '主仆', desc: '园丁', strength: 4, time: '1890' },
    { sourceId: 'h2', targetId: 'h9', relationType: '主仆', desc: '管家', strength: 5, time: '1890' },
    { sourceId: 'h2', targetId: 'h11', relationType: '主仆', desc: '女仆长，火灾失踪', strength: 4, time: '1892' },
    { sourceId: 'h2', targetId: 'h14', relationType: '同窗', desc: '镇医，同窗旧识', strength: 5, time: '1885' },
    { sourceId: 'h1', targetId: 'h13', relationType: '主仆', desc: '马车夫，夜行未归', strength: 3, time: '1890' },
    { sourceId: 'h1', targetId: 's1', relationType: '关联', desc: '预言师十三份讣告之一', strength: 3, time: '1893' },
    /* ---- 卡尔弗特家族 ---- */
    { sourceId: 'c1', targetId: 'c7', relationType: '兄弟', desc: '法官与宪兵上校', strength: 7, time: '1885' },
    { sourceId: 'c1', targetId: 'c2', relationType: '叔侄', desc: '接任家主', strength: 6, time: '1911' },
    { sourceId: 'c2', targetId: 'c3', relationType: '母子', desc: '长子', strength: 9, time: '1925' },
    { sourceId: 'c2', targetId: 'c4', relationType: '母子', desc: '次子，坠山', strength: 9, time: '1930' },
    { sourceId: 'c2', targetId: 'c5', relationType: '母女', desc: '作家', strength: 8, time: '1935' },
    { sourceId: 'c5', targetId: 'c10', relationType: '姐弟', desc: '幼弟，签约卖家', strength: 7, time: '1960' },
    { sourceId: 'c5', targetId: 'c11', relationType: '堂姐妹', desc: '档案保管人', strength: 6, time: '1955' },
    { sourceId: 'c7', targetId: 'c8', relationType: '主仆', desc: '歌女座上宾', strength: 4, time: '1910' },
    { sourceId: 'c1', targetId: 'c12', relationType: '祖孙', desc: '契约研究者', strength: 5, time: '1930' },
    { sourceId: 'c12', targetId: 's8', relationType: '师徒', desc: '渡鸦祭司的引路人', strength: 5, time: '1940' },
    /* ---- 幽庭镇：镇民网 ---- */
    { sourceId: 't1', targetId: 't2', relationType: '同僚', desc: '镇长与牧师，共谋结案', strength: 6, time: '1893' },
    { sourceId: 't1', targetId: 'h2', relationType: '联手', desc: '火灾善后的默契', strength: 7, time: '1893' },
    { sourceId: 't2', targetId: 't4', relationType: '对手', desc: '牧师与女巫的道统之争', strength: 5, time: '1895' },
    { sourceId: 't2', targetId: 't22', relationType: '同僚', desc: '意外逝者名单', strength: 3, time: '1893' },
    { sourceId: 't3', targetId: 't20', relationType: '闺蜜', desc: '梦簿与铅字记者', strength: 5, time: '1900' },
    { sourceId: 't13', targetId: 't21', relationType: '朋友', desc: '邮差与医生，信与签名', strength: 4, time: '1928' },
    { sourceId: 't5', targetId: 't16', relationType: '同窗', desc: '钟表匠与教师', strength: 4, time: '1890' },
    { sourceId: 't6', targetId: 't12', relationType: '盟友', desc: '面包与杂货的情报网', strength: 4, time: '1910' },
    { sourceId: 't8', targetId: 't13', relationType: '同僚', desc: '警长与邮差', strength: 4, time: '1915' },
    { sourceId: 't8', targetId: 't22', relationType: '同僚', desc: '警长与殡葬师', strength: 4, time: '1920' },
    { sourceId: 't9', targetId: 't20', relationType: '朋友', desc: '渔夫与记者，雾与报道', strength: 4, time: '1930' },
    { sourceId: 't10', targetId: 't18', relationType: '夫妻', desc: '寡妇与酒鬼，真话', strength: 6, time: '1895' },
    { sourceId: 't11', targetId: 't14', relationType: '夫妻', desc: '助产士与木工', strength: 7, time: '1900' },
    { sourceId: 't11', targetId: 'h1', relationType: '敌对', desc: '被隐瞒啼哭的孩子', strength: 5, time: '1910' },
    { sourceId: 't15', targetId: 'w1', relationType: '联手', desc: '铁衣与守夜会', strength: 6, time: '1897' },
    { sourceId: 't16', targetId: 't17', relationType: '师徒', desc: '教师与学生（摇篮鬼）', strength: 8, time: '1909' },
    { sourceId: 't17', targetId: 'g3', relationType: '创造', desc: '死灵化形：摇篮鬼', strength: 9, time: '1910' },
    { sourceId: 't19', targetId: 'g5', relationType: '创造', desc: '孤儿托比化为迷宫鬼童', strength: 9, time: '1915' },
    { sourceId: 't20', targetId: 'h14', relationType: '盟友', desc: '记者向镇医索证', strength: 4, time: '1895' },
    { sourceId: 't21', targetId: 'h14', relationType: '师徒', desc: '手记接手人', strength: 4, time: '1925' },
    { sourceId: 't7', targetId: 't18', relationType: '主仆', desc: '旅店老板与酒鬼房客', strength: 3, time: '1900' },
    { sourceId: 't12', targetId: 'g1', relationType: '关联', desc: '账本上买蜡烛的灰衣女士', strength: 3, time: '1910' },
    /* ---- 守夜会 ---- */
    { sourceId: 'w1', targetId: 'w7', relationType: '师徒', desc: '前后任会长，交棒与自缢', strength: 7, time: '1895' },
    { sourceId: 'w1', targetId: 'w2', relationType: '主仆', desc: '会长与执事', strength: 6, time: '1900' },
    { sourceId: 'w1', targetId: 'w3', relationType: '师徒', desc: '学徒失踪', strength: 8, time: '1917' },
    { sourceId: 'w1', targetId: 'w6', relationType: '同窗', desc: '会长与顾问', strength: 6, time: '1895' },
    { sourceId: 'w2', targetId: 'w5', relationType: '同僚', desc: '执事与文书', strength: 5, time: '1920' },
    { sourceId: 'w4', targetId: 'w1', relationType: '联手', desc: '禁书注释与守夜', strength: 6, time: '1905' },
    { sourceId: 'w7', targetId: 'w8', relationType: '师徒', desc: '前任会长与法师', strength: 7, time: '1892' },
    { sourceId: 'w9', targetId: 'w8', relationType: '同事', desc: '圣兵与法师', strength: 5, time: '1905' },
    { sourceId: 'w10', targetId: 'w2', relationType: '同僚', desc: '缝尸人与执事', strength: 4, time: '1925' },
    { sourceId: 'w1', targetId: 'w11', relationType: '父子', desc: '战后继任之子，守夜血脉', strength: 8, time: '1920' },
    { sourceId: 'w11', targetId: 'c12', relationType: '联手', desc: '战后会长与研究者', strength: 6, time: '1972' },
    /* ---- 灵体与生者的恩怨 ---- */
    { sourceId: 'g1', targetId: 'h2', relationType: '敌对', desc: '长姐对封档的兄长', strength: 7, time: '1910' },
    { sourceId: 'g1', targetId: 'a1', relationType: '盟友', desc: '灰衣女士与七爷百年默契', strength: 8, time: '1910' },
    { sourceId: 'g2', targetId: 'h1', relationType: '依附', desc: '火焰夫人依附家主而生', strength: 9, time: '1893' },
    { sourceId: 'g2', targetId: 'g1', relationType: '对手', desc: '恶灵与守宅灵的对立', strength: 8, time: '1893' },
    { sourceId: 'g2', targetId: 'n10', relationType: '依附', desc: '2026 年附体巴兹，火借人形', strength: 9, time: '2026' },
    { sourceId: 'g6', targetId: 't4', relationType: '依附', desc: '井中新娘与守井人', strength: 8, time: '1910' },
    { sourceId: 'g6', targetId: 'h2', relationType: '敌对', desc: '怨于父辈的安排', strength: 7, time: '1910' },
    { sourceId: 'g8', targetId: 'h9', relationType: '敌对', desc: '血手园丁对管家的恨', strength: 6, time: '1896' },
    { sourceId: 'g8', targetId: 'h2', relationType: '敌对', desc: '误判自缢的怨', strength: 6, time: '1896' },
    { sourceId: 'g10', targetId: 'g6', relationType: '联手', desc: '雾中骑手与井中新娘，同困百年的执念', strength: 5, time: '1942' },
    { sourceId: 'g10', targetId: 'h3', relationType: '恋人', desc: '骑手生前的暗恋（送信对象）', strength: 8, time: '1893' },
    { sourceId: 'g4', targetId: 't5', relationType: '依附', desc: '吊钟鬼与钟表匠', strength: 6, time: '1920' },
    { sourceId: 'g4', targetId: 's6', relationType: '联手', desc: '敲钟与巡魂的抗争', strength: 5, time: '1930' },
    { sourceId: 'g13', targetId: 's5', relationType: '依附', desc: '地下室小孩与摆灯人', strength: 5, time: '1977' },
    { sourceId: 'g13', targetId: 'g9', relationType: '祖孙', desc: '孤儿院魂与疗养院魂，旧院同根', strength: 6, time: '1977' },
    { sourceId: 'g11', targetId: 'c5', relationType: '依附', desc: '镜中双人缠着作家', strength: 5, time: '1963' },
    { sourceId: 'g12', targetId: 'c7', relationType: '依附', desc: '风铃女与上校', strength: 6, time: '1932' },
    { sourceId: 'g14', targetId: 'a1', relationType: '双胞胎', desc: '七爷的分灵', strength: 9, time: '1920' },
    { sourceId: 'g7', targetId: 'a1', relationType: '盟友', desc: '石像鬼只认七爷', strength: 7, time: '1893' },
    { sourceId: 's2', targetId: 'h3', relationType: '救赎', desc: '传话人替灰衣女士传音', strength: 6, time: '1910' },
    { sourceId: 's4', targetId: 't3', relationType: '依附', desc: '梦魇织者与药剂师的梦', strength: 5, time: '1920' },
    { sourceId: 's3', targetId: 'h13', relationType: '救赎', desc: '船夫渡走马车夫', strength: 5, time: '1893' },
    { sourceId: 's7', targetId: 't13', relationType: '联手', desc: '收灵人与邮差的信', strength: 4, time: '1945' },
    { sourceId: 's8', targetId: 'a3', relationType: '师徒', desc: '渡鸦祭司与乌鸦使者', strength: 8, time: '1893' },
    { sourceId: 's1', targetId: 'g2', relationType: '对手', desc: '预言师与恶灵的对峙', strength: 6, time: '1893' },
    { sourceId: 's5', targetId: 's6', relationType: '同僚', desc: '摆灯人与巡魂人', strength: 5, time: '1930' },
    /* ---- 动物网 ---- */
    { sourceId: 'a1', targetId: 'a5', relationType: '盟友', desc: '百年前并肩的旧识', strength: 9, time: '1893' },
    { sourceId: 'a1', targetId: 'a12', relationType: '师徒', desc: '传人幼崽月', strength: 8, time: '2025' },
    { sourceId: 'a1', targetId: 'a7', relationType: '盟友', desc: '金翅雀代传多年', strength: 7, time: '1920' },
    { sourceId: 'a1', targetId: 'n13', relationType: '救赎', desc: '被猫咖收留的“休假”', strength: 5, time: '2020' },
    { sourceId: 'a5', targetId: 'n2', relationType: '救赎', desc: '救过的“不像狼的狼”', strength: 8, time: '2025' },
    { sourceId: 'a3', targetId: 'g2', relationType: '对手', desc: '偷走半页契约的鸦', strength: 5, time: '1900' },
    { sourceId: 'a4', targetId: 'w1', relationType: '主仆', desc: '守夜犬', strength: 7, time: '1898' },
    { sourceId: 'a8', targetId: 'g6', relationType: '盟友', desc: '井中蛇灵与新娘', strength: 8, time: '1910' },
    { sourceId: 'a10', targetId: 'g4', relationType: '对手', desc: '鼠先知搬家引开吊钟鬼', strength: 4, time: '1928' },
    { sourceId: 'a11', targetId: 'g1', relationType: '盟友', desc: '蝶妖领路进 1893', strength: 6, time: '1915' },
    { sourceId: 'a9', targetId: 's5', relationType: '同僚', desc: '鸮与摆灯人换班巡夜', strength: 5, time: '1950' },
    { sourceId: 'a6', targetId: 'g10', relationType: '创造', desc: '白马为骑手所化', strength: 9, time: '1942' },
    /* ---- 当代线 ---- */
    { sourceId: 'n1', targetId: 'n2', relationType: '恋人', desc: '租客与侦探，从委托到并肩', strength: 8, time: '2024' },
    { sourceId: 'n1', targetId: 'n7', relationType: '主仆', desc: '租客与房东', strength: 4, time: '2023' },
    { sourceId: 'n7', targetId: 'n8', relationType: '主仆', desc: '房东与承包商', strength: 4, time: '2024' },
    { sourceId: 'n2', targetId: 'n17', relationType: '同僚', desc: '侦探与夜巡警', strength: 6, time: '2024' },
    { sourceId: 'n2', targetId: 'n5', relationType: '同僚', desc: '侦探与法医', strength: 6, time: '2024' },
    { sourceId: 'n5', targetId: 'n1', relationType: '关联', desc: '法医听伊芙琳讲“遗嘱”', strength: 4, time: '2024' },
    { sourceId: 'n10', targetId: 'n3', relationType: '同僚', desc: '博主与主播的互相引流', strength: 5, time: '2025' },
    { sourceId: 'n10', targetId: 'n9', relationType: '对手', desc: '同行竞争，都在拍老宅', strength: 6, time: '2025' },
    { sourceId: 'n10', targetId: 'n14', relationType: '对手', desc: '抢挖契约石的冲突', strength: 5, time: '2025' },
    { sourceId: 'n10', targetId: 'n11', relationType: '同窗', desc: '大学同学，被催眠找“记忆”', strength: 6, time: '2015' },
    { sourceId: 'n10', targetId: 'n15', relationType: '同僚', desc: '借阅旧档的窗口', strength: 5, time: '2023' },
    { sourceId: 'n1', targetId: 'n11', relationType: '主仆', desc: '心理师与访客', strength: 5, time: '2024' },
    { sourceId: 'n1', targetId: 'a2', relationType: '创造', desc: '收养黑猫墨玉', strength: 8, time: '2023' },
    { sourceId: 'n1', targetId: 'a12', relationType: '创造', desc: '抱回幼崽月', strength: 8, time: '2025' },
    { sourceId: 'n4', targetId: 'n15', relationType: '同僚', desc: '老记者与档案员', strength: 6, time: '2018' },
    { sourceId: 'n4', targetId: 'n12', relationType: '对手', desc: '记者与镇长候选人的“封口”', strength: 4, time: '2024' },
    { sourceId: 'n12', targetId: 't1', relationType: '祖孙', desc: '曾祖父沙利文镇长', strength: 6, time: '1893' },
    { sourceId: 'n13', targetId: 'n18', relationType: '同窗', desc: '猫咖与咖啡店老板', strength: 5, time: '2016' },
    { sourceId: 'n16', targetId: 'n17', relationType: '母子', desc: '高中生与巡警', strength: 8, time: '2013' },
    { sourceId: 'n16', targetId: 'a4', relationType: '主仆', desc: '遛狗少年与猎犬', strength: 7, time: '2025' },
    { sourceId: 'n6', targetId: 'a2', relationType: '朋友', desc: '助理与猫的纸箱之约', strength: 4, time: '2024' },
    { sourceId: 'n1', targetId: 'g1', relationType: '救赎', desc: '灰衣女士引路守护她', strength: 9, time: '2023' },
    { sourceId: 'n2', targetId: 'g10', relationType: '救赎', desc: '雾中骑手为他指路', strength: 6, time: '2024' },
    { sourceId: 'n1', targetId: 'g6', relationType: '对手', desc: '井中新娘的试探', strength: 6, time: '2025' },
    { sourceId: 'n3', targetId: 'n10', relationType: '盟友', desc: '报道与博主的默契', strength: 4, time: '2025' },
    { sourceId: 'n1', targetId: 'n14', relationType: '联手', desc: '契约石出土的合作破译', strength: 7, time: '2025' },
    { sourceId: 'n14', targetId: 'n15', relationType: '同僚', desc: '考古与档案', strength: 5, time: '2025' },
    { sourceId: 'n11', targetId: 'n1', relationType: '师徒', desc: '催眠下的记忆回溯', strength: 6, time: '2024' },
    { sourceId: 'n10', targetId: 'a1', relationType: '对手', desc: '博主想献祭七爷换“完整记忆”', strength: 7, time: '2026' },
    { sourceId: 'a12', targetId: 'n1', relationType: '救赎', desc: '幼崽守护新主人', strength: 8, time: '2026' },
    /* ---- 跨时代串联（疑案指向同一仪式） ---- */
    { sourceId: 'h1', targetId: 'c1', relationType: '盟友', desc: '五姓契约：霍桑与卡尔弗特', strength: 9, time: '1893' },
    { sourceId: 'h1', targetId: 't1', relationType: '盟友', desc: '五姓契约：镇长家', strength: 8, time: '1893' },
    { sourceId: 'h1', targetId: 'w7', relationType: '对手', desc: '驱魔人阻止仪式', strength: 7, time: '1895' },
    { sourceId: 'h1', targetId: 'g2', relationType: '创造', desc: '第一命死于其手，恶灵萌芽', strength: 9, time: '1893' },
    { sourceId: 'h3', targetId: 'h2', relationType: '敌对', desc: '封档之争', strength: 7, time: '1910' },
    { sourceId: 'h2', targetId: 'c12', relationType: '敌对', desc: '研究者索要档案', strength: 5, time: '1930' },
    { sourceId: 'c12', targetId: 'w11', relationType: '盟友', desc: '“四姓换一命”共识', strength: 7, time: '1972' },
    { sourceId: 'w11', targetId: 'n10', relationType: '祖孙', desc: '血脉相传，守夜遗名', strength: 9, time: '1988' },
    { sourceId: 'n10', targetId: 'n1', relationType: '对手', desc: '两条调查线终局的交汇', strength: 8, time: '2025' },
    { sourceId: 'n2', targetId: 'n10', relationType: '对手', desc: '侦探锁定博主的破绽', strength: 8, time: '2026' },
    { sourceId: 'g2', targetId: 'n1', relationType: '敌对', desc: '恶灵的“债务”就是她本人', strength: 9, time: '2026' },
    { sourceId: 'g2', targetId: 'g7', relationType: '对手', desc: '石像鬼拼死守门', strength: 7, time: '2026' },
    { sourceId: 'g1', targetId: 'g2', relationType: '敌对', desc: '百年守宅灵与火的最后对决', strength: 9, time: '2026' },
    { sourceId: 'a7', targetId: 'n10', relationType: '关联', desc: '第七封信送至执行者手中', strength: 8, time: '2026' },
    { sourceId: 'a1', targetId: 's3', relationType: '盟友', desc: '七爷与船夫的最后交易', strength: 8, time: '2026' },
    { sourceId: 'n1', targetId: 'a1', relationType: '救赎', desc: '七爷替她挡下“换命”的代价', strength: 9, time: '2026' },
    { sourceId: 'n2', targetId: 'g2', relationType: '敌对', desc: '侦探以真话为渡船之票', strength: 8, time: '2026' }
  ],

  events: [
    { title: '幽庭大火', time: '1893-10-13', era: '火世纪', desc: '霍桑宅一夜大火，女仆埃达失踪，全镇以为“鸦灾”结案——五姓契约由此埋下第一粒灰。', persons: ['老埃尔玛·霍桑', '弗朗西斯·霍桑', '伊莱扎·霍桑', '埃达'] },
    { title: '十三份讣告', time: '1893-10-12', era: '火世纪', desc: '预言师赛姬送出十三份讣告，只有一份寄出——寄给了当年的马车夫。', persons: ['赛姬', '乔治'] },
    { title: '灰猫入夜', time: '1893-10-14', era: '火世纪', desc: '火灾次夜，一只灰猫蹲在宅门口，谁开窗它都不走；老珀尔给它留了牛奶。', persons: ['灰猫七爷', '老珀尔'] },
    { title: '玫瑰棚之死', time: '1896-05-02', era: '火世纪', desc: '老珀尔被指纵火者，自缢于玫瑰棚；此后血手园丁的怨灵常驻花园。', persons: ['老珀尔', '弗朗西斯·霍桑', '布洛克'] },
    { title: '铁衣护符', time: '1897-01-20', era: '火世纪', desc: '奥列格打出三副铁护符护住全家，守夜会会长奥古斯都携白猫蜡烛进宅。', persons: ['奥列格', '奥古斯都·佩尔', '灰猫七爷'] },
    { title: '封井', time: '1900-08-08', era: '火世纪', desc: '女巫伊莫金封住老井，井口埋下一片金翅雀羽毛；井中新娘的婚书从此无人得见。', persons: ['伊莫金', '玛格丽特·霍桑', '弗朗西斯·霍桑'] },
    { title: '灰衣坠楼', time: '1910-01-04', era: '火世纪', desc: '伊莱扎从三楼坠下，死前说“锁好 1893”；当晚长明灯亮，灰衣女士自此守宅。', persons: ['伊莱扎·霍桑', '灰衣女士'] },
    { title: '井中骊歌', time: '1910-06-17', era: '火世纪', desc: '玛格丽特投井，婚书背面写“我不愿”；井中新娘在月圆夜唱旧曲。', persons: ['玛格丽特·霍桑', '弗朗西斯·霍桑', '伊莫金'] },
    { title: '十三响之钟', time: '1928-12-25', era: '余火', desc: '钟楼钟声自鸣十三下，第六响时全镇灯火齐灭；老鼠先知带队搬离钟楼。', persons: ['索尔', '吊钟鬼', '老鼠先知'] },
    { title: '烛台与纸页', time: '1936-11-11', era: '余火', desc: '守夜会会长奥古斯都死于自家烛台旁，学徒拉文失踪，纸上写满“她回来了”。', persons: ['奥古斯都·佩尔', '拉文', '海伦'] },
    { title: '空袭夜的地窖', time: '1944-02-19', era: '余火', desc: '空袭警报夜，镇民躲进霍桑宅地窖，出来时有人说看见“火里有人笑”。', persons: ['修伯特·霍桑', '温妮莎·卡尔弗特', '凯瑟琳'] },
    { title: '疗养院铁链', time: '1955-09-14', era: '余火', desc: '疗养院一夜间十床病人集体“睡着”，走廊尽头拖链声至今未绝。', persons: ['铁链老奶奶', '梦魇织者'] },
    { title: '镜中双人', time: '1963-04-01', era: '余火', desc: '更衣室长镜里出现一哭一笑的两个人，镜面敲碎后自愈；作家写下第四章。', persons: ['埃莉诺·卡尔弗特', '镜中双人'] },
    { title: '契约研究者失踪', time: '1974-03-16', era: '余火', desc: '本杰明在研究记录里写下“不是五姓，是四姓换一命”，当晚失踪。', persons: ['本杰明·卡尔弗特', '查尔斯·佩尔'] },
    { title: '孤儿院火光', time: '1977-07-30', era: '余火', desc: '旧孤儿院失火，地下室女孩未寻获；她画的火柴人烧不坏。', persons: ['地下室小女孩', '摆灯人'] },
    { title: '保险柜落锁', time: '1980-02-02', era: '余火', desc: '查尔斯·佩尔将契约锁进保险柜，对外宣布“仪式已解”——真相只锁了一半。', persons: ['查尔斯·佩尔'] },
    { title: '买宅', time: '2001-10-03', era: '长夜归', desc: '图勒买下霍桑宅，中介隐瞒“附赠住客”；他在第一夜听到阁楼心跳声。', persons: ['图勒', '石像鬼守护'] },
    { title: '第七封信', time: '2012-05-05', era: '长夜归', desc: '塞西莉亚留下未寄出的“第七封信”与一张灰猫照片；信纸背面是一次性铅笔写的地址。', persons: ['塞西莉亚·卡尔弗特', '金翅雀信使'] },
    { title: '博主开档', time: '2018-11-01', era: '长夜归', desc: '巴兹开播《幽庭档案》，第一期看浏览量破百万；片尾的猫叫声无人注意。', persons: ['巴兹', '灰猫七爷'] },
    { title: '伊芙琳入住', time: '2023-09-09', era: '长夜归', desc: '伊芙琳住进老宅，黑猫墨玉堵住阁楼梯；当晚她梦见 1893 年的婚礼。', persons: ['伊芙琳·格里姆', '黑猫墨玉', '图勒'] },
    { title: '探灵直播', time: '2025-02-14', era: '长夜归', desc: '薇拉夜探直播，弹幕说她身后站着一个灰衣女人——后台同事说“你身后没人”。', persons: ['薇拉', '灰衣女士'] },
    { title: '契约石出土', time: '2025-06-21', era: '长夜归', desc: '所罗门挖出刻着四个姓氏与一道手印的契约石；手印比契约早了一年。', persons: ['所罗门', '伊芙琳·格里姆', '雨果·克劳斯'] },
    { title: '房东坠梯', time: '2024-12-24', era: '长夜归', desc: '图勒从阁楼梯摔落，临终说“第七封……是猫送来的”；法医发现第三层抓痕。', persons: ['图勒', '林恩', '灰猫七爷'] },
    { title: '蛇灵问话', time: '2025-10-31', era: '长夜归', desc: '娜迦尼在井口拦住伊芙琳：“你把什么换走了？”——她答不上来。', persons: ['娜迦尼', '伊芙琳·格里姆', '井中新娘'] },
    { title: '满月仪式夜', time: '2026-02-07', era: '长夜归', desc: '巴兹主持“完整换命”仪式，灰衣女士拼死相护；附体真相揭晓——执行者从一开始就在镜头前。', persons: ['巴兹', '火焰夫人', '灰衣女士', '伊芙琳·格里姆'] },
    { title: '猫的代价', time: '2026-02-08', era: '黎明', desc: '七爷替伊芙琳挡下换命的代价，玄狼阿赫自林中归来；证人只有一只幼崽月。', persons: ['灰猫七爷', '玄狼阿赫', '灰猫幼崽月'] },
    { title: '黎明解除', time: '2026-02-09', era: '黎明', desc: '雨果以一句真话换渡船，蝴蝶引两人回到 1893 年的那晚；烧掉契约，长夜结束。', persons: ['雨果·克劳斯', '伊芙琳·格里姆', '蝶妖', '忘川船夫'] },
    { title: '第七封信寄出', time: '2026-02-14', era: '黎明', desc: '金翅雀信使衔走最后一封“第七封信”；贝蒂在专档末页盖上“已阅”。', persons: ['金翅雀信使', '贝蒂', '灰衣女士'] },
    { title: '小镇的早晨', time: '2026-02-15', era: '黎明', desc: '钟楼只敲十二下，铁链声停，井水清澈；伊芙琳在门口放了两碗牛奶。', persons: ['伊芙琳·格里姆', '灰猫幼崽月', '猫头鹰守夜人'] }
  ]
};
